- id: '1586328747853'
  alias: Boot
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data: {}
    service: shell_command.var_set_values
  - data: {}
    service: shell_command.select_set_options
  - data: {}
    service: shell_command.text_set_values
