#### A
automation: !include automations.yaml
automation old: !include_dir_merge_list include/automations/

#### C
config:

#### D
# DEFAULT_CONFIG
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
device_tracker: !include include/device_trackers.yaml

#### F
# FRONTEND
frontend:
  themes: !include_dir_merge_named themes

#### G
group: !include_dir_merge_named include/groups/

#### H
homeassistant:
  customize: !include_dir_merge_named include/customize/
  packages: !include_dir_merge_named include/packages/

#### I
input_select: !include_dir_merge_named include/input/select/

##### L
light: !include_dir_merge_list include/lights/
# LOVELACE MODE
lovelace:
  mode: yaml
  resources: !include_dir_merge_list include/resources/

# LOVELACE GEN
lovelace_gen:

#### R
recorder:
  db_url: !secret MYSQL_URL
  
remote_homeassistant:
  instances:
  - host: 192.168.0.13
    port: 8123
    secure: false
    verify_ssl: false
    access_token: !secret REMOTE_HA_API
    include:
      domains:
      - light
      - switch
      - sensor

rest_command: !include_dir_merge_named include/rest_commands/

#### S
sensor: !include_dir_merge_list include/sensors/
shell_command: !include_dir_merge_named include/shell_commands/

#### T
tts:
  - platform: google_translate
    language: "da"

tuya:
  username: !secret TUYA_USERNAME
  password: !secret TUYA_PASSWORD
  country_code: !secret TUYA_COUNTRY
  platform: smart_life

#### V
var: !include_dir_merge_named include/variables/